global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'metrics'
    scrape_interval: 5s
    static_configs:
      #--------------dispatcher-----------------------client 1-2-3---------------------wh-dispatcher------wh-filter
      - targets: ['localhost:8090','localhost:8080','localhost:8081','localhost:8082','localhost:8180','localhost:8190']
