{
 "title": "Event distribution with Kafka and Webhook",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clients Received Callback",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(base_REST_request_total{instance=\"localhost:8080\"}[1m])",
     "legendFormat": "Client 1 : 8080"
    },
    {
     "expr": "increase(base_REST_request_total{instance=\"localhost:8081\"}[1m])",
     "legendFormat": "Client 2 : 8081"
    },
    {
     "expr": "increase(base_REST_request_total{instance=\"localhost:8082\"}[1m])",
     "legendFormat": "Client 3 : 8082"
    },
    {
     "expr": "increase(base_REST_request_total{method=\"createEvent\"}[1m])",
     "legendFormat": "Event created"
    },
    {
     "expr": "increase(application_br_com_helpdev_webhook_config_WebhookDispatcherPublisher_publishPerformedChecks_total[1m])",
     "legendFormat": "Events filtred"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(base_REST_request_total{method=\"createEvent\"}[1m])",
     "legendFormat": "Event creator : 8090"
    },
    {
     "expr": "increase(application_br_com_helpdev_webhook_KafkaWebhookFilter_performedChecks_total[1m])",
     "legendFormat": "Webhook filter : received"
    },
    {
     "expr": "increase(application_br_com_helpdev_webhook_config_WebhookDispatcherPublisher_publishPerformedChecks_total[1m])",
     "legendFormat": "Webhook filter : filtred"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{instance=\"localhost:8190\"}",
     "legendFormat": "Webhook Filter"
    },
    {
     "expr": "base_thread_count{instance=\"localhost:8180\"}",
     "legendFormat": "Webhook Dispatcher"
    },
    {
     "expr": "base_thread_count{instance=\"localhost:8090\"}",
     "legendFormat": "Event creator"
    }
   ]
  },
  {
   "title": "Webhook Filter - Time processor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(application_br_com_helpdev_webhook_KafkaWebhookFilter_checksTimer_seconds[1m]) * 1000",
     "legendFormat": "p {{ quantile }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{instance=\"localhost:8190\"} * 1000",
     "legendFormat": "Webhook Filter"
    },
    {
     "expr": "base_cpu_processCpuLoad_percent{instance=\"localhost:8180\"} * 1000",
     "legendFormat": "Webhook Dispatcher"
    },
    {
     "expr": "base_cpu_processCpuLoad_percent{instance=\"localhost:8090\"} * 1000",
     "legendFormat": "Event Creator"
    }
   ]
  }
 ]
}